name: "Dev.to Sync Articles"

on:
  workflow_dispatch:

jobs:
  update-readme:
    name: "Sync Articles from dev.to"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull articles
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/shiftescape"